services:
  ecommerce:
    image: famtwen/ecommerce_mongodb:latest
    container_name: ecommerce_mongodb
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data_ecommerce:/app/data 
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

